### PR TITLE
PSW-2: Automatically fix ESLint/stylelint errors on save in VSCode

### PR DESCRIPTION
**Pull request by joshua-scott**
https://wunder.atlassian.net/jira/software/projects/PSW/boards/302?selectedIssue=PSW-2.

- Adds recommended extensions for ESLint and stylelint; this will prompt the user to install the extensions when the repo is opened in Code for the first time
- Enables automatic fixing of ESLint/stylelint errors on save

The same change has been made to `drupal-project` here: https://github.com/wunderio/drupal-project/pull/151

### CODE REVIEW

**Comment by dcorb** [comment]
Does prettier work for you on these new files?  (Not sure if it's because the extension .json)
I think normally prettier adds one line break at the end of the file (you wouldn't see the red icon)

image


Maybe it's because vscode not allowing to access the .vscode folder

**Comment by dcorb** [comment]
The extension StyleLint is suggested, so this works 👍 
image

In the instructions of StyleLint plugin recommends disabling the built-in vscode css validator (css.validate: false) But not sure if we should do it or not. @joshua-scott  ? I spent 20 minutes looking for more information about this topic (in vscode repo and stylelint repo, and I couldn't find almost any information)
https://github.com/stylelint/vscode-stylelint

It prevents double-validation: (it seems built-in vscode picks up the stylelint rules too)
image


Then, I went to check rules marked "autofixable", https://stylelint.io/user-guide/rules/list#possible-errors
and I tested that autofixes the rule  `no-empty-first-line': true, `

I had these 2 extra rules when testing (to make it easier).
  ```
module.exports = {
  processors: ['stylelint-processor-styled-components'],
  extends: [
    'stylelint-config-recommended',
    'stylelint-config-styled-components',
    'stylelint-config-prettier',
  ],
  rules: {
    'no-empty-first-line': true,
    'unit-whitelist': ['px'],
  },
};

};
```

**Comment by dcorb** [comment]
For me is ready to merge, except prettier'ifying these 2 new files.
And maybe we want to discuss more the issue of double validation?

**Comment by dcorb** [comment]
I opened this issue on the Extension repository https://github.com/stylelint/vscode-stylelint/issues/149 
I would suggest continuing with double-validation for now, it's not so annoying

**Comment by dcorb** [comment]
Also we could add a comment in the json file about this _"We discourage their use in favor of using the built-in syntaxes as processors are incompatible with the autofix feature."_   (It seems styled components and autofix is not compatible https://stylelint.io/user-guide/configure#processors)

**Comment by joshua-scott** [comment]
@dcorb thanks for your comments.

Re: lack of a newline at the end of the JSON files - fixed in 6b0b81f.

Re: double validation - I'm not experiencing that, even though I apparently have `css.validate` set to `true` which seems to be VSCode's default. I guess we can leave it for now as you suggested.

**Review by dcorb — APPROVED** [review]

**Pull request merged**
